version: "3"
services:
  db:
    container_name: examen_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Ci_Cd_DB 
    restart: always
    image: mysql:latest
     ports:
      - "3306:3306"
    networks:
     - AppNet
  
 spring-boot:
    depends_on:
      - db
    container_name: spring
    ports:
      - "8083:8083"
    image: SeifeddineBS/Ci_Cd_DBexamthourayas2
    networks:
      - AppNet 
    restart: on-failure
    
networks:
  AppNet:
    driver: bridge



